### ISSUE TITLE
Update for node LTS 10

### ISSUE THREAD

**Issue by justinphelps** [NorthernMan54/homebridge-mcuiot#26]
fs.js:129
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:129:9)
    at Object.writeFile (fs.js:1159:14)
    at storeToken (/opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/mcuiot-logger/logger.js:220:8)
    at /opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/mcuiot-logger/logger.js:201:13
    at /opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)

homebridge@homebridge:/opt/node/lib/node_modules/homebridge-acurite-temperature/node_modules/mcuiot-logger$ node --version
v10.15.0

**Comment by NorthernMan54** [comment]
Justin, give me a day or 2 to investigate this.

**Comment by NorthernMan54** [comment]
Found the issue, please reinstall the plugin, and redo the google authentication step.
