### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mstrQ** [NorthernMan54/homebridge-mcuiot#31]
Hello,
with the latest version I am getting the following error.
Homebridge is then entering a restart loop.

```
[MCUIOT] configureAccessory MCUIOT Reset Switch
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-CD2B3
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-CD2B3
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-5D2CF8
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-5D2CF8
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-5CFCBE
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-5CFCBE
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-5D53E
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-5D53E
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-2AA86A
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-2AA86A
[6/28/2019, 6:00:05 PM] [MCUIOT] configureAccessory NODE-5D1C37
[6/28/2019, 6:00:05 PM] [MCUIOT] Reading MCUIOT: NODE-5D1C37
[6/28/2019, 6:00:05 PM] [MCUIOT] Starting Bonjour listener
[6/28/2019, 6:00:05 PM] [MCUIOT] Web Server listening on: http://localhost:8080
[6/28/2019, 6:00:05 PM] SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at mcuiot.<anonymous> (/homebridge/node_modules/homebridge-mcuiot/index.js:279:23)
    at Request._callback (/homebridge/node_modules/homebridge-mcuiot/index.js:763:7)
    at Request.self.callback (/homebridge/node_modules/homebridge-mcuiot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-mcuiot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-mcuiot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
[6/28/2019, 6:00:05 PM] Got SIGTERM, shutting down Homebridge...
```

Any ideas? Thanks in advance.

**Comment by NorthernMan54** [comment]
Line 279 is this

response = JSON.parse(responseBody);

Which it trying to parse the response from the device into a JSON object and it is failing as the response object isn't a JSON object

I have added logic to trap this exception and give a meaningful message.  Please update to version v0.1.66

**Comment by mstrQ** [comment]
That fixed it. working now.
Thanks so much, great work.

**Comment by NorthernMan54** [comment]
I think one of your devices may not be working though, check the logs
